# Generated by Django 5.2.12 on 2026-04-07 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('awarded_score', models.PositiveIntegerField(default=0, verbose_name='Начислено баллов')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.CharField(max_length=255, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('question_type', models.CharField(choices=[('single_choice', 'Один правильный'), ('multiple_choice', 'Несколько правильных'), ('true_false', 'True / False')], max_length=32, verbose_name='Тип вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Баллы')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('passing_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Проходной балл')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Максимальный балл')),
                ('lesson_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lessons.lessonblock', verbose_name='Блок урока')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Балл')),
                ('passed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
                'ordering': ('-started_at',),
            },
        ),
    ]
