# Generated by Django 5.2.12 on 2026-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_ai_draft',
            field=models.BooleanField(default=False, verbose_name='AI-черновик'),
        ),
    ]
