# Generated by Django 5.2.12 on 2026-04-13 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_normalize_categories'),
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('provider_name', models.CharField(default='openrouter', max_length=50, verbose_name='Провайдер')),
                ('external_model_id', models.CharField(max_length=255, verbose_name='Внешний model id')),
                ('display_name', models.CharField(max_length=255, verbose_name='Отображаемое имя')),
                ('role_type', models.CharField(choices=[('fast', 'Быстрая'), ('balanced', 'Сбалансированная'), ('strong', 'Сильная')], max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('context_window', models.PositiveIntegerField(default=0, verbose_name='Размер контекста')),
                ('supports_structured_output', models.BooleanField(default=False, verbose_name='Поддерживает structured output')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
            ],
            options={
                'verbose_name': 'AI-модель',
                'verbose_name_plural': 'AI-модели',
                'ordering': ('role_type', 'display_name'),
                'constraints': [models.UniqueConstraint(fields=('provider_name', 'external_model_id'), name='unique_ai_model_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('action_type', models.CharField(choices=[('qa', 'Вопрос по курсу'), ('quiz_generation', 'Генерация теста'), ('model_selection', 'Выбор модели')], max_length=30, verbose_name='Тип действия')),
                ('selected_model_label', models.CharField(blank=True, max_length=255, verbose_name='Снимок model id')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка')], default='success', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='courses.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='lessons.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('selected_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_logs', to='ai_support.aimodeloption', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Лог AI-взаимодействия',
                'verbose_name_plural': 'Логи AI-взаимодействий',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('selected_role_type', models.CharField(choices=[('fast', 'Быстрая'), ('balanced', 'Сбалансированная'), ('strong', 'Сильная')], default='balanced', max_length=20, verbose_name='Выбранная роль модели')),
                ('selected_model_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preferences', to='ai_support.aimodeloption', verbose_name='Выбранная модель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preference', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка AI-пользователя',
                'verbose_name_plural': 'Настройки AI-пользователей',
            },
        ),
    ]
