services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mycourse-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      SQLITE_NAME: /app/data/db.sqlite3
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost
      SITE_DOMAIN: 127.0.0.1:8000
    volumes:
      - ./db.sqlite3:/app/data/db.sqlite3
      - ./media:/app/media
    restart: unless-stopped
