# Generated by Django 5.2.12 on 2026-04-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='not_started', max_length=20, verbose_name='Статус')),
                ('completed_manually', models.BooleanField(default=False, verbose_name='Завершен вручную')),
                ('best_score', models.PositiveIntegerField(default=0, verbose_name='Лучший балл')),
            ],
            options={
                'verbose_name': 'Прогресс урока',
                'verbose_name_plural': 'Прогресс уроков',
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершен')], default='not_started', max_length=20, verbose_name='Статус')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='Прогресс, %')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='courses.course', verbose_name='Курс')),
                ('last_opened_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.lesson', verbose_name='Последний открытый урок')),
            ],
            options={
                'verbose_name': 'Прогресс курса',
                'verbose_name_plural': 'Прогресс курсов',
            },
        ),
    ]
