# Generated by Django 5.2.12 on 2026-04-07 14:24

import apps.core.utils
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Оценочная длительность, мин.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('code', 'Код'), ('file', 'Файл'), ('quote', 'Цитата/заметка'), ('quiz', 'Тест')], max_length=20, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('content_markdown', models.TextField(blank=True, verbose_name='Markdown контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadToPath('lesson_images'), validators=[apps.core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Разрешены только JPG, JPEG, PNG и WEBP.')], verbose_name='Изображение')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.core.utils.UploadToPath('lesson_files'), validators=[apps.core.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Разрешены только PDF-файлы.')], verbose_name='Файл')),
                ('code_language', models.CharField(blank=True, max_length=50, verbose_name='Язык кода')),
                ('code_content', models.TextField(blank=True, verbose_name='Код')),
                ('note_style', models.CharField(blank=True, choices=[('note', 'Заметка'), ('quote', 'Цитата')], default='note', max_length=20, verbose_name='Стиль заметки')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный блок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Блок урока',
                'verbose_name_plural': 'Блоки уроков',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description_markdown', models.TextField(verbose_name='Описание')),
                ('language', models.CharField(default='python', max_length=50, verbose_name='Язык')),
                ('starter_code', models.TextField(blank=True, verbose_name='Стартовый код')),
                ('expected_output_description', models.TextField(blank=True, verbose_name='Ожидаемый результат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_placeholder', models.BooleanField(default=True, verbose_name='Заглушка')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_tasks', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Практическое задание',
                'verbose_name_plural': 'Практические задания',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='unique_lesson_slug_in_course'),
        ),
    ]
